import greenfoot.*;

public class Map1 extends Spielfeld {

    public Map1() {
        super(30, 20, 30);
        prepare();
        punkteVerteilen();
    }

    /**
     * Bereite die Welt für den Programmstart vor.
     * Das heißt: Erzeuge die Anfangs-Objekte und füge sie der Welt hinzu.
     */
    private void prepare()
    {
        addObject(new Wand(), 6, 15);
        Wand wand = new Wand();
        addObject(wand,2,2);
        Wand wand2 = new Wand();
        addObject(wand2,2,3);
        Wand wand3 = new Wand();
        addObject(wand3,2,4);
        Wand wand4 = new Wand();
        addObject(wand4,2,5);
        Wand wand5 = new Wand();
        addObject(wand5,2,6);
        Wand wand6 = new Wand();
        addObject(wand6,2,7);
        Wand wand7 = new Wand();
        addObject(wand7,2,8);
        Wand wand8 = new Wand();
        addObject(wand8,2,9);
        Wand wand9 = new Wand();
        addObject(wand9,2,10);
        Wand wand10 = new Wand();
        addObject(wand10,2,12);
        Wand wand11 = new Wand();
        addObject(wand11,2,12);
        Wand wand12 = new Wand();
        addObject(wand12,3,12);
        Wand wand13 = new Wand();
        addObject(wand13,4,12);
        Wand wand14 = new Wand();
        addObject(wand14,2,14);
        Wand wand15 = new Wand();
        addObject(wand15,3,14);
        Wand wand16 = new Wand();
        addObject(wand16,4,14);
        Wand wand17 = new Wand();
        addObject(wand17,5,14);
        Wand wand18 = new Wand();
        addObject(wand18,6,14);
        Wand wand19 = new Wand();
        addObject(wand19,6,12);
        Wand wand20 = new Wand();
        addObject(wand20,6,13);
        Wand wand21 = new Wand();
        addObject(wand21,4,10);
        Wand wand22 = new Wand();
        addObject(wand22,5,10);
        Wand wand23 = new Wand();
        addObject(wand23,6,10);
        Wand wand24 = new Wand();
        addObject(wand24,4,7);
        Wand wand25 = new Wand();
        addObject(wand25,4,9);
        Wand wand26 = new Wand();
        addObject(wand26,4,8);
        Wand wand27 = new Wand();
        addObject(wand27,6,8);
        Wand wand28 = new Wand();
        addObject(wand28,7,8);
        Wand wand29 = new Wand();
        addObject(wand29,4,5);
        Wand wand30 = new Wand();
        addObject(wand30,4,4);
        Wand wand31 = new Wand();
        addObject(wand31,4,3);
        Wand wand32 = new Wand();
        addObject(wand32,4,2);
        Wand wand33 = new Wand();
        addObject(wand33,6,1);
        Wand wand34 = new Wand();
        addObject(wand34,6,2);
        Wand wand35 = new Wand();
        addObject(wand35,6,4);
        Wand wand36 = new Wand();
        addObject(wand36,6,3);
        Wand wand37 = new Wand();
        addObject(wand37,6,6);
        Wand wand38 = new Wand();
        addObject(wand38,7,6);
        Wand wand39 = new Wand();
        addObject(wand39,8,6);
        Wand wand40 = new Wand();
        addObject(wand40,8,2);
        Wand wand41 = new Wand();
        addObject(wand41,8,3);
        Wand wand42 = new Wand();
        addObject(wand42,8,4);
        Wand wand43 = new Wand();
        addObject(wand43,8,5);
        Wand wand44 = new Wand();
        addObject(wand44,10,1);
        Wand wand45 = new Wand();
        addObject(wand45,10,2);
        Wand wand46 = new Wand();
        addObject(wand46,10,3);
        Wand wand47 = new Wand();
        addObject(wand47,10,4);
        Wand wand48 = new Wand();
        addObject(wand48,10,5);
        Wand wand49 = new Wand();
        addObject(wand49,10,6);
        Wand wand50 = new Wand();
        addObject(wand50,10,7);
        Wand wand51 = new Wand();
        addObject(wand51,10,9);
        Wand wand52 = new Wand();
        addObject(wand52,10,11);
        Wand wand53 = new Wand();
        addObject(wand53,10,8);
        Wand wand54 = new Wand();
        addObject(wand54,10,10);
        Wand wand55 = new Wand();
        addObject(wand55,10,12);
        Wand wand56 = new Wand();
        addObject(wand56,10,13);
        Wand wand57 = new Wand();
        addObject(wand57,10,14);
        Wand wand58 = new Wand();
        addObject(wand58,10,15);
        Wand wand59 = new Wand();
        addObject(wand59,10,16);
        Wand wand60 = new Wand();
        addObject(wand60,10,17);
        Wand wand61 = new Wand();
        addObject(wand61,10,18);
        Wand wand62 = new Wand();
        addObject(wand62,2,17);
        Wand wand63 = new Wand();
        addObject(wand63,2,16);
        Wand wand64 = new Wand();
        addObject(wand64,4,16);
        Wand wand65 = new Wand();
        addObject(wand65,4,17);
        Wand wand66 = new Wand();
        addObject(wand66,4,18);
        Wand wand67 = new Wand();
        addObject(wand67,7,15);
        Wand wand68 = new Wand();
        addObject(wand68,7,14);
        Wand wand69 = new Wand();
        addObject(wand69,7,16);
        Wand wand70 = new Wand();
        addObject(wand70,7,17);
        Wand wand71 = new Wand();
        addObject(wand71,6,16);
        Wand wand72 = new Wand();
        addObject(wand72,6,17);
        Wand wand73 = new Wand();
        addObject(wand73,9,16);
        Wand wand74 = new Wand();
        addObject(wand74,9,17);
        Wand wand75 = new Wand();
        addObject(wand75,9,18);
        Wand wand76 = new Wand();
        addObject(wand76,9,14);
        Wand wand77 = new Wand();
        addObject(wand77,9,15);
        Wand wand78 = new Wand();
        addObject(wand78,9,13);
        Wand wand79 = new Wand();
        addObject(wand79,9,12);
        Wand wand80 = new Wand();
        addObject(wand80,8,12);
        removeObject(wand79);
        removeObject(wand78);
        Wand wand81 = new Wand();
        addObject(wand81,8,10);
        Wand wand82 = new Wand();
        addObject(wand82,8,11);
        Wand wand83 = new Wand();
        addObject(wand83,9,8);
    }
}
