import greenfoot.*;

public class Map1 extends Spielfeld {
    public Map1() {
        super(30, 20, 38,
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOXXXXXOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOXOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOXOXOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOXXXXXOOOOOOOOOOOOX;" +
            "XOXOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOXXXXOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOSOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
