import greenfoot.*;

public class Map2 extends Spielfeld {
    public Map2() {
        super(30, 20, 30,
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOXXXXXOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
