public class Map2 extends StatusInfoSpielfeld {
    public Map2() {
        super(30, 20, 38,
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOXXXXXOOOOOOOOOOOOOGOOOOOOOOX;" +
            "XOXOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOXOXOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOXXXXXOOOOOOOOOOOOX;" +
            "XOXOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOXXXXOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOSOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0.005);
    }
}
