import greenfoot.*;

public class Map2 extends Spielfeld {
    public Map2() {
        super(30, 20, 38,
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOXXXXXOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOXOOOOOOOOGOOOOOOOOOOOOOOOOOX;" +
            "XOXOXOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOXXXXXOOOOOOOOOOOOX;" +
            "XOXOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOXXXXOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOGOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOSOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX;" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
