import greenfoot.*;
public class Map5 extends StatusInfoSpielfeld {
    public Map5() {
        super(29, 20, 30,
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;" +
            "XGOOXOOOOOOOOOOOOOOOOXXXXOOGX;" +
            "XOXOOOXXXXOXOXXOXXXXOXOOOOXOX;" +
            "XOXOXOOOOOOXOOOOOOXOOXOXXOXOX;" +
            "XOOOXOXOXXOXOXXXXOXOXOOOOOXOX;" +
            "XOXOXOXOXOOOOOXOOOXOOOXOXOOOX;" +
            "XOXOOOOOOOXXXOOOXOXXOXXOXOXXX;" +
            "XOXXXOXXXOOOXXOXXOOOOXOOXOOOX;" +
            "XOOOOOXOOOXOXOOOXOXXOOOXXXXOX;" +
            "XXXXXOXOXXXOOOSOOOOOOXOOOOOOX;" +
            "XOOOOOOOOOOOXOOOXOXXOXOXOXXXX;" +
            "XOXXXXXOXXXOXXOXXOXXOXOXOOOOX;" +
            "XOOOOOOOOOXOOOOOXOOOOXOXOXXOX;" +
            "XXXXOXXXXOXOXOXOXXXXOOOXOOOOX;" +
            "XOOOOOOOOOXOOOXOOOOOOXOXXOXXX;" +
            "XOXXXXXXOXXXOXXOXXXOXXOXOOOOX;" +
            "XOOOOOOXOOOOOXOOOOXOXXOOOXXOX;" +
            "XOXXXXOXXXXXOXOXXOXOOOOXXXXOX;" +
            "XGOOOOOOOOOOOOOXXOOOXXOOOOOGX;" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0.005); 
    }
}